### ISSUE TITLE
Error: Point does not lie on the curve

### ISSUE THREAD

**Issue by kosinusbch** [RenzoDD/digibyte-js#1]
Hey, trying to create an address from a private key and it spits out the following error.

```
Error: Point does not lie on the curve
at Point.validate (/location/node_modules/digibyte-js/lib/crypto/point.js:119:11)
at new PublicKey (/location/node_modules/digibyte-js/lib/publickey.js:53:14)
at Function.PublicKey.fromPrivateKey (/location/node_modules/digibyte-js/lib/publickey.js:221:10)
at PrivateKey.toPublicKey (/location/node_modules/digibyte-js/lib/privatekey.js:361:30)
at PrivateKey.toAddress (/location/node_modules/digibyte-js/lib/privatekey.js:375:21)
at Object.create (/location/coins/dgb.js:164:33)
at /location/src/generic.js:80:79
at new Promise (<anonymous>)
at generate (/location/src/generic.js:64:12)
at /location/src/generic.js:88:29
at new Promise (<anonymous>)
at Object.finalize (/location/src/generic.js:87:12)
at /location/routes/api.js:9:17
at Layer.handle [as handle_request] (/location/node_modules/express/lib/router/layer.js:95:5)
at next (/location/node_modules/express/lib/router/route.js:137:13)
at cors (/location/node_modules/cors/lib/index.js:188:7)
```

Not really sure what the issue could be considering I'm literally just doing this:

```
const bitcore = require('digibyte-js')

[...]

let private = new bitcore.PrivateKey()
let doc = {
  address: private.toAddress(),
  wif: private.toWIF(),
}
```

**Comment by RenzoDD** [comment]
Hi, I couldn't replicate the error. Could you provide more info?
![Screenshot_1](https://user-images.githubusercontent.com/55367961/154442669-cd9a7cae-0f43-43a0-903f-002d501a7055.png)

**Comment by kosinusbch** [comment]
@RenzoDD oh shit yeah just tried to set up a fresh project to see if I can replicate it, but looks like the issue is actually due to bitcore-lib and digibyte-js being included in different files at the same time. For some reason including this library creates the error
```
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
```

I solved this by just adding return; to the top of the versionGuard function in digibyte-js like so

```
bitcore.versionGuard = function(version) {
  return;
  [...]
}
```

Which then causes the "Error: Point does not lie on the curve"

Any way to more cleanly resolve this conflict? My project has about a dozen different versions of bitcore-lib for different coins and this is the first time I came across this problem

**Comment by RenzoDD** [comment]
I'm going to change the version guard in future commits. I'm just need to be sure that that won't cause any problem with other bitcore-forks libraries
